# /etc/filebeat/filebeat.yml

filebeat.inputs:
- type: log
  paths:
    - "/usr/local/bro/logs/current/conn.log"
  fields:
    type: "bro-conn"
  fields_under_root: true

- type: log
  paths:
    - "/usr/local/bro/logs/current/dns.log"
  fields:
    type: "bro-dns"
  fields_under_root: true

- type: log
  paths:
    - "/usr/local/bro/logs/current/files.log"
  fields:
    type: "bro-files"
  fields_under_root: true

- type: log
  paths:
    - "/usr/local/bro/logs/current/http.log"
  fields:
    type: "bro-http"
  fields_under_root: true

- type: log
  paths:
    - "/usr/local/bro/logs/current/notice.log"
  fields:
    type: "bro-notice"
  fields_under_root: true

- type: log
  paths:
    - "/usr/local/bro/logs/current/ssh.log"
  fields:
    type: "bro-ssh"
  fields_under_root: true

- type: log
  paths:
    - "/usr/local/bro/logs/current/ssl.log"
  fields:
    type: "bro-ssl"
  fields_under_root: true

- type: log
  paths:
    - "/usr/local/bro/logs/current/weird.log"
  fields:
    type: "bro-weird"
  fields_under_root: true

- type: log
  paths:
    - "/usr/local/bro/logs/current/x509.log"
  fields:
    type: "bro-x509"
  fields_under_root: true

output.logstash:
  # The Logstash hosts
  hosts: ["8.8.8.8:5044"]
